# Generated by Django 2.1.8 on 2019-04-25 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friendings',
            field=models.ManyToManyField(blank=True, related_name='friendeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
